@startuml
Client --> GameServer: PACKET_ID_GAME_BATTING_REQ

GameServer --> Client: PACKET_ID_GAME_BATTING_RES

note over GameServer: 방에 있는 모든 유저들
GameServer --> Client: PACKET_ID_GAME_BATTING_NTF

note over GameServer: 모두 배팅 했거나 or 대기 시간이 지나면 게임 결과를 보낸다
GameServer --> Client: PACKET_ID_GAME_RESULT_NTF
note right GameServer: 일정 시간이 지나면 게임 플레이 가능
@enduml