package protocol

const (
	ERROR_CODE_NONE = 1

	ERROR_CODE_PACKET_DECODING_FAIL           = 51
	ERROR_CODE_PACKET_NOT_LOGIN_USER          = 52
	ERROR_CODE_ROOM_NOT_REGISTED_PACKET_ID = 53
	ERROR_CODE_USER_NOT_IN_ROOM = 54

	ERROR_CODE_DISCONNECT_UNAUTHENTICATED_USER = 61

	ERROR_CODE_LOGIN_USER_DUPLICATION  = 111
	ERROR_CODE_LOGIN_USER_INVALID_ID   = 112

	ERROR_CODE_ROOM_NOT_IN_USER                    = 121
	ERROR_CODE_ROOM_INVALIDE_NUMBER                = 122

	ERROR_CODE_ENTER_ROOM_ALREADY = 131
	ERROR_CODE_ENTER_ROOM_PREV_WORKING = 132
	ERROR_CODE_ENTER_ROOM_INVALID_USER_ID = 133
	ERROR_CODE_ENTER_ROOM_USER_FULL = 134
	ERROR_CODE_ENTER_ROOM_DUPLCATION_USER         = 135
	ERROR_CODE_ENTER_ROOM_INVALID_SESSION_STATE    = 136
	ERROR_CODE_ENTER_ROOM_AUTO_ROOM_NUMBER = 137

	ERROR_CODE_LEAVE_ROOM_INTERNAL_INVALID_USER    = 141

	ERROR_CODE_ROOM_CHAT_CHAT_MSG_LEN    = 151

	ERROR_CODE_ROOM_RELAY_FAIL_DECPDING    = 161

	ERROR_CODE_ROOM_NOT_REGISTED_INTERNAL_PACKET_ID = 252 // 번역 필요없음


)
